### ISSUE TITLE
ADT A01 v2.3 - Getting Repetition Count 1 instead of 0  When Segment not Present

### ISSUE THREAD

**Issue by HimanshuSinghal1990** [duaneedwards/nHapi#18] opened 2015-03-28 18:53 UTC
Hi Everyone ,

When i am parsing the hl7 message, when segment is not present it gives the repetition count = 1 instead of 0.

HL 7 Message Grammar : {MSH},{EVN},{PID},{PD1},{NK1},{PV1},{PV2},{GT1},{IN1},{IN2}

Code :
IMessage parsedMessage = null;
PipeParser parser = new PipeParser();
parsedMessage = parser.Parse(message);
ADT_A01 a01 = messageParsed as ADT_A01;

![screenshot-1](https://cloud.githubusercontent.com/assets/4537637/6882376/c7d2e494-d5a8-11e4-99b4-30250843f1c5.jpg)

As you can see in above image DB1,  DG1, AL1, OBX are few segments which are not present still repetition count is 1

I am getting this problem with all other types of messages also .

**Comment by HimanshuSinghal1990** [comment] 2015-04-06 07:26
Can anyone Help me out  on this . Really Urgent.

**Comment by duaneedwards** [comment] 2015-04-23 02:17
Duplicate of #16

**Closed by duaneedwards** 2015-04-23 02:17 UTC
