### ISSUE TITLE
How to validate a 2.3 standard message ?

### ISSUE THREAD

**Issue by ohadinho** [duaneedwards/nHapi#42] opened 2015-10-15 06:19 UTC
Hi,
There is no documentation at all of how should a user validate a message with this project.
Can someone assist ?

**Comment by duaneedwards** [comment] 2016-07-15 06:33
Closing as this is a duplicate of #46 Missing conformance profile validation

**Closed by duaneedwards** 2016-07-15 06:33 UTC

**Comment by milkshakeuk** [comment] 2022-02-02 09:01
@ohadinho there are some useful tutorials on validating with nhapi [here](https://saravanansubramanian.com/hl7tutorials/#hl7-programming-tutorials-using-nhapi-and-net).
